# shellcheck shell=bash
# apt_extract: install a Debian package without root. "apt-get download"
# fetches the .deb through apt's own signed chain (InRelease -> Packages ->
# sha256) from the running suite, and "dpkg-deb -x" unpacks it under
# ~/.local/opt/apt/<package>. Library packages it needs that are not
# installed are unpacked next to it, and ~/.local/bin gets a small wrapper
# that sets LD_LIBRARY_PATH to those library folders only.

# apt_installed PKG: true when dpkg reports PKG as installed.
apt_installed() {
  [ "$(dpkg-query -W -f='${db:Status-Abbrev}' "$1" 2>/dev/null)" = "ii " ]
}

# apt_lib_deps PKG: the library packages PKG depends on (first alternative of
# each Depends/Pre-Depends entry, lib* only; perl modules and -dev skipped).
apt_lib_deps() {
  apt-cache show --no-all-versions "$1" 2>/dev/null |
    sed -n 's/^\(Pre-\)\{0,1\}Depends: //p' |
    tr ',' '\n' |
    sed 's/|.*//; s/(.*//; s/:.*//; s/[[:space:]]//g' |
    grep '^lib' | grep -v -e '-perl$' -e '-dev$' || true
}

# apt_closure PKG: PKG plus every missing library package it needs.
apt_closure() {
  local queue="$1" seen=" " p d
  while [ -n "$queue" ]; do
    p=${queue%% *}
    case $queue in *" "*) queue=${queue#* } ;; *) queue= ;; esac
    case $seen in *" $p "*) continue ;; esac
    seen="$seen$p "
    printf '%s\n' "$p"
    for d in $(apt_lib_deps "$p"); do
      if ! apt_installed "$d"; then queue="${queue:+$queue }$d"; fi
    done
  done
}

# apt_candidate PKG: the version apt would install now (empty if unknown).
apt_candidate() {
  apt-cache show --no-all-versions "$1" 2>/dev/null | sed -n 's/^Version: //p' | head -n 1
}

# apt_unpacked PKG ROOT: the version of PKG unpacked under ROOT (from
# .dotfiles-ok, one "package version" line per unpacked .deb).
apt_unpacked() {
  awk -v p="$1" '$1 == p { print $2 }' "$2/.dotfiles-ok" 2>/dev/null
}

# apt_stale PKG ROOT: true when ROOT must be (re)unpacked: never unpacked,
# older than apt's candidate (Debian security updates arrive this way), or a
# library download failed last time.
apt_stale() {
  local want
  [ -f "$2/.dotfiles-ok" ] || return 0
  [ -s "$2/.dotfiles-missing" ] && return 0
  want=$(apt_candidate "$1")
  [ -n "$want" ] && [ "$(apt_unpacked "$1" "$2")" != "$want" ]
}

# apt_lib_path ROOT: colon list of the folders under ROOT that hold libraries.
apt_lib_path() {
  find "$1" \( -type f -o -type l \) -name 'lib*.so*' 2>/dev/null |
    sed 's|/[^/]*$||' | sort -u | tr '\n' ':' | sed 's/:$//'
}

# apt_wrapper NAME REAL LIBPATH [VAR=VALUE...]: write ~/.local/bin/NAME.
apt_wrapper() {
  local name=$1 real=$2 libpath=$3 kv
  shift 3
  for kv in "$real" "$libpath" "$@"; do
    quotable "$kv" || return 1
  done
  {
    printf '#!/bin/sh\n'
    printf '# Generated by dotfiles install.sh (apt_extract): runs %s unpacked\n' "$name"
    printf '# without root under ~/.local/opt/apt. Delete to undo.\n'
    if [ -n "$libpath" ]; then
      printf "LD_LIBRARY_PATH='%s'\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\n" "$libpath"
      printf 'export LD_LIBRARY_PATH\n'
    fi
    for kv in "$@"; do
      printf "%s='%s'\nexport %s\n" "${kv%%=*}" "${kv#*=}" "${kv%%=*}"
    done
    printf "exec '%s' \"\$@\"\n" "$real"
  } | write_file "$BIN_DIR/$name" 755
}

# apt_extract PKG BIN...: unpack PKG (+ missing libraries) and wrap each BIN
# (a path relative to the package root, e.g. usr/bin/wl-copy).
apt_extract() {
  local pkg=$1 root tmp p libpath bin missing='' env_git='' vflag=--version old
  shift
  root="$OPT_DIR/apt/$pkg"
  if ! have apt-get || ! have dpkg-deb || ! have dpkg-query; then
    report FAIL apt "$pkg: apt-get/dpkg-deb not found, cannot unpack without root"
    return 0
  fi
  if apt_stale "$pkg" "$root"; then
    old=$(apt_unpacked "$pkg" "$root")
    tmp=$(mktemp -d "${TMPDIR:-/tmp}/dotfiles-apt.XXXXXX")
    for p in $(apt_closure "$pkg"); do
      if ! (cd "$tmp" && apt-get download "$p" >/dev/null 2>&1); then
        if [ "$p" = "$pkg" ]; then
          rm -rf "$tmp"
          report FAIL apt "$pkg: apt-get download failed (apt source unreachable or blocked?)"
          return 0
        fi
        missing="$missing $p"
      fi
    done
    rm -rf "$root.tmp"
    mkdir -p "$root.tmp"
    for p in "$tmp"/*.deb; do
      dpkg-deb -x "$p" "$root.tmp"
      # shellcheck disable=SC2016 # dpkg's own ${Field} syntax, not shell
      dpkg-deb -W --showformat='${Package} ${Version}\n' "$p" >>"$root.tmp/.dotfiles-ok"
    done
    # Failed library downloads are retried on the next run.
    printf '%s' "$missing" >"$root.tmp/.dotfiles-missing"
    rm -rf "$tmp" "$root"
    mv "$root.tmp" "$root"
    changed "unpacked $pkg $(apt_unpacked "$pkg" "$root")${old:+ (was $old)} (+ $(($(wc -l <"$root/.dotfiles-ok") - 1)) libraries) into $(tilde "$root")"
  fi
  libpath=$(apt_lib_path "$root")
  # git finds its helpers (git-remote-https) and templates through these.
  if [ "$pkg" = git ]; then env_git="GIT_EXEC_PATH=$root/usr/lib/git-core"; fi
  if [ "$pkg" = tmux ]; then vflag=-V; fi
  for bin in "$@"; do
    if [ -n "$env_git" ]; then
      apt_wrapper "${bin##*/}" "$root/$bin" "$libpath" "$env_git" \
        "GIT_TEMPLATE_DIR=$root/usr/share/git-core/templates" || return 1
    else
      apt_wrapper "${bin##*/}" "$root/$bin" "$libpath" || return 1
    fi
  done
  bin=$1
  missing="$missing$(LD_LIBRARY_PATH="$libpath" ldd "$root/$bin" 2>/dev/null | awk '/not found/ {printf " %s", $1}')"
  if [ -n "$missing" ]; then
    report WARN apt "$pkg unpacked, but some libraries are missing:$missing"
  elif check_runs "${bin##*/}" "$vflag"; then
    report OK apt "${bin##*/}: Debian package $pkg unpacked in $(tilde "$root") (no root)"
  else
    report FAIL apt "${bin##*/} from $pkg does not run: $RUN_ERR"
  fi
}

# apt_need CMD PKG BIN...: use the system CMD when the system has one (and
# retire our wrappers once it does), else unpack PKG with apt_extract.
apt_need() {
  local cmd=$1 d sys='' bin
  shift
  for d in /usr/local/bin /usr/bin /bin; do
    if [ -z "$sys" ] && [ -x "$d/$cmd" ]; then sys="$d/$cmd"; fi
  done
  if [ -z "$sys" ]; then
    apt_extract "$@"
    return 0
  fi
  shift
  for bin in "$@"; do
    bin="$BIN_DIR/${bin##*/}"
    if [ -f "$bin" ] && grep -q '(apt_extract)' "$bin"; then backup "$bin"; fi
  done
  report OK apt "$cmd: system package ($sys)"
}

apt_step() {
  [ "$OS" = linux ] || return 0
  step "system packages without root (apt_extract)"
  apt_need git git usr/bin/git
  apt_need tmux tmux usr/bin/tmux
  apt_need wl-copy wl-clipboard usr/bin/wl-copy usr/bin/wl-paste
}
