# shellcheck shell=bash
# tools.lock rows: reading, filtering and installing the tar/bin/gz kinds.
# Each tool lands in a versioned ~/.local/opt/<name>-<version> directory with
# a .ok stamp holding the verified sha256, and is linked into ~/.local/bin.
# Rolling back is a tools.lock revert plus a re-run: old versions stay on disk.

LOCK_FILE="$REPO/tools.lock"

# The current row (set by lock_rows before each callback).
R_NAME='' R_VERSION='' R_TIER='' R_OS='' R_ARCH='' R_KIND='' R_URL='' R_SHA='' R_VERIFY='' R_EXTRA=''

# lock_rows KIND CALLBACK: call CALLBACK for every row of KIND that applies to
# this machine (os, arch, tier). The file is read on fd 3 so that commands in
# the callback cannot swallow it through stdin.
lock_rows() {
  local kind=$1 callback=$2 line
  while IFS= read -r line <&3 || [ -n "$line" ]; do
    case $line in '' | '#'*) continue ;; esac
    set -f # split the row into its columns, without glob expansion
    # shellcheck disable=SC2086
    set -- $line
    set +f
    if [ $# -ne 10 ]; then
      warn "tools.lock: skipping malformed row: $line"
      continue
    fi
    R_NAME=$1 R_VERSION=$2 R_TIER=$3 R_OS=$4 R_ARCH=$5
    R_KIND=$6 R_URL=$7 R_SHA=$8 R_VERIFY=$9 R_EXTRA=${10}
    [ "$R_KIND" = "$kind" ] || continue
    row_applies || continue
    "$callback"
  done 3<"$LOCK_FILE"
}

# row_applies: true when the current row is for this OS, arch and tier.
row_applies() {
  case $R_OS in any | "$OS") ;; *) return 1 ;; esac
  case $R_ARCH in any | "$ARCH") ;; *) return 1 ;; esac
  if [ "$R_TIER" = dev ] && [ "$TIER" != dev ]; then return 1; fi
  return 0
}

# extra KEY: value of KEY in the current row's extra column (empty if unset).
extra() {
  local rest=$R_EXTRA item
  while [ -n "$rest" ]; do
    item=${rest%%;*}
    case $item in "$1="*) printf '%s' "${item#*=}" && return 0 ;; esac
    case $rest in *";"*) rest=${rest#*;} ;; *) rest= ;; esac
  done
  return 0
}

# row_blocker: print why the current row cannot be used here (empty = usable).
row_blocker() {
  local need_glibc need
  need_glibc=$(extra glibc)
  if [ -n "$need_glibc" ] && ! version_ge "${GLIBC:-0}" "$need_glibc"; then
    printf 'needs glibc %s, this system has %s' "$need_glibc" "${GLIBC:-none}"
    return 0
  fi
  need=$(extra needs)
  if [ -n "$need" ] && ! have "$need"; then
    printf 'needs %s, which is not installed' "$need"
  fi
}

# row_dir: versioned install directory of the current row.
row_dir() { printf '%s/%s-%s' "$OPT_DIR" "$R_NAME" "$R_VERSION"; }

# install_row: install the current tar/bin/gz row (check first, then apply).
# Sets ROW_BIN to the installed executable. Returns 1 on failure.
ROW_BIN=
install_row() {
  local dir bin_rel tmp name file
  dir=$(row_dir)
  case $R_NAME in *[!A-Za-z0-9._-]*) warn "bad tool name: $R_NAME" && return 1 ;; esac
  case $R_KIND in
    tar)
      bin_rel=$(extra bin)
      safe_relpath "$bin_rel" || {
        warn "$R_NAME: bad bin= path in tools.lock"
        return 1
      }
      ;;
    bin | gz) bin_rel=$R_NAME ;;
    *) return 1 ;;
  esac
  ROW_BIN="$dir/$bin_rel"
  if [ -f "$dir/.ok" ] && [ "$(cat "$dir/.ok")" = "$R_SHA" ] && [ -x "$ROW_BIN" ]; then
    return 0
  fi
  file=$(fetch_verified "$R_URL" "$R_SHA") || return 1
  tmp="$dir.tmp"
  rm -rf "$tmp"
  mkdir -p "$tmp"
  case $R_KIND in
    tar) tar -xf "$file" -C "$tmp" || return 1 ;;
    gz) gunzip -c "$file" >"$tmp/$R_NAME" || return 1 ;;
    bin) cp "$file" "$tmp/$R_NAME" ;;
  esac
  name="$tmp/$bin_rel"
  [ -f "$name" ] || {
    warn "$R_NAME: $bin_rel not found in the download"
    return 1
  }
  chmod 755 "$name"
  printf '%s\n' "$R_SHA" >"$tmp/.ok"
  rm -rf "$dir"
  mv "$tmp" "$dir"
  changed "installed $R_NAME $R_VERSION in $(tilde "$dir")"
}

# link_bin NAME REAL: put REAL on PATH as ~/.local/bin/NAME. With icu=wrap and
# no libicu, NAME becomes a small wrapper that switches .NET to invariant mode.
link_bin() {
  local name=$1 real=$2
  if [ "$(extra icu)" = wrap ] && [ "$HAVE_ICU" != yes ]; then
    quotable "$real" || return 1
    write_file "$BIN_DIR/$name" 755 <<EOF
#!/bin/sh
# Generated by dotfiles install.sh: libicu is not installed, so run
# $name in .NET invariant globalization mode (no ICU needed).
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
exec '$real' "\$@"
EOF
    return 0
  fi
  link "$real" "$BIN_DIR/$name"
}

# check_runs NAME [FLAG]: true when ~/.local/bin/NAME --version (or FLAG)
# works. Catches a binary that cannot run here (wrong libc, missing loader).
RUN_ERR=
check_runs() {
  RUN_ERR=$("$BIN_DIR/$1" "${2:---version}" 2>&1 >/dev/null </dev/null) && return 0
  RUN_ERR=$(printf '%s' "$RUN_ERR" | head -n 1)
  return 1
}

# pin_source VERIFY: how the pinned sha256 was established (for the report).
pin_source() {
  case $1 in
    digest) echo "pinned from the GitHub digest" ;;
    checksum) echo "pinned, matches the vendor checksum file" ;;
    attest) echo "pinned, attestation verified" ;;
    tofu) echo "pinned at first download" ;;
    *) echo "pin: $1" ;;
  esac
}

# tools_row: callback for one tar/bin/gz row (the nvim row is handled by
# lib/nvim.sh).
tools_row() {
  local why link_name
  [ "$R_NAME" = nvim ] && return 0
  why=$(row_blocker)
  if [ -n "$why" ]; then
    report SKIP tools "$R_NAME $R_VERSION: $why"
    return 0
  fi
  if ! install_row; then
    report FAIL tools "$R_NAME $R_VERSION: download or sha256 check failed ($R_URL)"
    return 0
  fi
  link_name=$(basename "$ROW_BIN")
  link_bin "$link_name" "$ROW_BIN"
  if check_runs "$link_name"; then
    local note=''
    if [ "$(extra icu)" = wrap ] && [ "$HAVE_ICU" != yes ]; then note="; no libicu, so via a wrapper"; fi
    report OK tools "$link_name $R_VERSION (sha256 OK, $(pin_source "$R_VERIFY")$note)"
  else
    report FAIL tools "$link_name $R_VERSION installed but does not run: $RUN_ERR"
  fi
}

tools_step() {
  step "tools (tools.lock)"
  if [ "$OS" != linux ]; then
    report OK tools "macOS uses the Brewfile for these tools"
    return 0
  fi
  lock_rows tar tools_row
  lock_rows bin tools_row
  lock_rows gz tools_row
}
